#Playbook to retrieve DNAC device inventory
- hosts: localhost
# This calls localhost as we're just interacting with a REST API endpoint.

  vars_files:
    - vars.yml

  tasks:

  - name: Get Token
    uri:
      url: "{{ dnac_url }}api/system/v1/auth/token"
      # Calling a Login URL
      method: POST
      user: "{{ dnac_user }}"
      password: "{{ dnac_password }}"
      force_basic_auth: yes
      headers:
        Content-Type: "application/json"
      return_content: no
      validate_certs: no
      # And don't validate the server cert as it's self-signed for non-prod.
    register: token


  - name: Get network_devices
    uri:
      url: "{{ dnac_url }}api/v1/network-device/"
      # the main API endpoint
      method: GET
      # This is a GET request.
      headers:
        Content-Type: "application/json"
        Cookie: "X-JWT-ACCESS-TOKEN={{token.json.Token}}"
      return_content: no
      validate_certs: no
    register: network_device


  - name: Inventory Details
    #debug: var=network_device
    debug: msg="{{ network_device.json.response }}"

  - name: Inventory Details to File
    local_action: copy content={{ network_device.json.response }} dest=dnac-inventory.json
